// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAyVM04fTN5f1yYLDryQ_gcqYM-Z7d7Q',
    appId: '1:303636925271:web:02c89383b2efd81e2b8c12',
    messagingSenderId: '303636925271',
    projectId: 'wholesaler-dev',
    authDomain: 'wholesaler-dev.firebaseapp.com',
    databaseURL:
        'https://wholesaler-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wholesaler-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK4IjI1ggo5L8uaZd9jdKw-Nc3NpJLkCY',
    appId: '1:303636925271:android:4d080ac38c588e002b8c12',
    messagingSenderId: '303636925271',
    projectId: 'wholesaler-dev',
    databaseURL:
        'https://wholesaler-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wholesaler-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcRkp3IFn3WZnjS7yAZw67FH26GtAa_M',
    appId: '1:303636925271:ios:ac4619535a9689272b8c12',
    messagingSenderId: '303636925271',
    projectId: 'wholesaler-dev',
    databaseURL:
        'https://wholesaler-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wholesaler-dev.appspot.com',
    iosClientId:
        '303636925271-qhraqarsnta7f4gs1voqrhmvulntd54j.apps.googleusercontent.com',
    iosBundleId: 'com.wholesaler.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcRkp3IFn3WZnjS7yAZw67FH26GtAa_M',
    appId: '1:303636925271:ios:ac4619535a9689272b8c12',
    messagingSenderId: '303636925271',
    projectId: 'wholesaler-dev',
    databaseURL:
        'https://wholesaler-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wholesaler-dev.appspot.com',
    iosClientId:
        '303636925271-qhraqarsnta7f4gs1voqrhmvulntd54j.apps.googleusercontent.com',
    iosBundleId: 'com.wholesaler.dev',
  );
}
