// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stage.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EU5VV_pKChsQwC2MWCfK4UAIoP2eCrI',
    appId: '1:735972555882:web:c8611b90e9ad0c55ba1e13',
    messagingSenderId: '735972555882',
    projectId: 'enfa-stage',
    authDomain: 'enfa-stage.firebaseapp.com',
    databaseURL:
        'https://enfa-stage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'enfa-stage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ohJLXPSJY_IDNWCc6RW8XI3ROg4Nirg',
    appId: '1:735972555882:android:6e769e33472a1cbcba1e13',
    messagingSenderId: '735972555882',
    projectId: 'enfa-stage',
    databaseURL:
        'https://enfa-stage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'enfa-stage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnj1nJIwUN2r-TsS-_xg5X0pHSr-pYraM',
    appId: '1:735972555882:ios:807d5855df53628aba1e13',
    messagingSenderId: '735972555882',
    projectId: 'enfa-stage',
    databaseURL:
        'https://enfa-stage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'enfa-stage.appspot.com',
    iosBundleId: 'com.enfa.stage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnj1nJIwUN2r-TsS-_xg5X0pHSr-pYraM',
    appId: '1:735972555882:ios:807d5855df53628aba1e13',
    messagingSenderId: '735972555882',
    projectId: 'enfa-stage',
    databaseURL:
        'https://enfa-stage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'enfa-stage.appspot.com',
    iosBundleId: 'com.enfa.stage',
  );
}
